[project]
name = "aip-backtest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.34.0",
    "pyarrow>=21.0.0",
    "yfinance>=0.2.66",
]
